# Site settings
title: Shake it
email: aj@soulshake.net
description: > # this means to ignore newlines until "baseurl:"
  Hello there! You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://soulshake.net" # the base hostname & protocol for your site
twitter_username: s0ulshake
github_username: soulshake 

# Build settings
markdown: kramdown

